sudo: required
language: minimal

git:
  depth: 2

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/iloop-to-model
    - IMAGE_TAG=travis-ci-test
    - IMAGE=${IMAGE_REPO}:${IMAGE_TAG}

before_install:
  - echo ${DOCKER_PASSWORD} | docker login -u=decaftravis --password-stdin

install:
  - docker build -t ${IMAGE} .
  - make setup

script:
  - make test-travis
  - make flake8
  - make isort
  - make license

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker tag ${IMAGE} ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker tag ${IMAGE} ${IMAGE_REPO}:${TRAVIS_BRANCH}
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "ieXH15CBpPSo/tgzmBosEVQMScqbp2QttXGM1qhMZkp7O6tVBLSyj+ZfwlopaymTBLrJ+79i4RqYR8b9BAHylTmoPz+SpZ9HDG1zZBKwkKOLBNXTvHYVlWEbwdaKVk/st4npDIr7KhdgY1gGvHJJuB3mobzQ0S4Uo2PXUqVgjCnV22k8qEfdVc9Qck2q2eFvRkqKYxfDiBQA9ch0C71D/Knwc8MxBCCAqC73FQCypJ/eOZRCDKypzOfKiz4eSBXA8rIEbgzVqS3a7Ff3orHfsb+LWxp4r7NXY7oUn55TLEQdI8U1Na+1MAlMVMVjAM0hZxT0ZB7s5l6UluK2yrOKM4SzE0Oq93RsA6V9eouqMZemynlAPfqhdk2RlT8UTeWsDfjqgNFI3xdeQWQ7Li8/xyvI21l/vO/O96U+7Y/UHFKznXriu/UyraZ/5WTvXdgpcpwCgfuiAeGevtRV6Ji1FjavbLlnvYpYuh/IQ4XMdAx4TFB/weAPRt0uzKRyO7EJGru5MA4oPc2XTcI8YTBuHrr9vp9ezttre7R9zMVaO7O4AheNNkLv9fotkkku+r1nQ1Wgp8xua8bmrp7vlFpUH/A/PGsNxJkhFC+D5C472G9/CNK6dO7XstX9ibA3jOhXR7Sp+jmu+unU4j50/GWBUkSNIQZJW5a5dfkE/9PwCRU="
    on_success: change
    on_failure: always
    on_pull_requests: false
