version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/dd-decaf-cfbf6/iloop-to-model:${IMAGE_TAG:-latest}
    ports:
      - "${ILOOP_TO_MODEL_PORT:-7000}:7000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
      - ENVIRONMENT=development
      - ILOOP_TOKEN
      - ILOOP_API=${ILOOP_API:-http://iloop-backend:80/api}
      - MODEL_API=${MODEL_API:-http://model-backend:8000}
    command: gunicorn -c gunicorn.py iloop_to_model.app:get_app()
    networks:
      DD-DeCaF:
        aliases:
          - iloop-to-model

networks:
  DD-DeCaF:
    external: true
