web:
  build: .
  dockerfile: Dockerfile
  ports:
    - 7000:7000
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONASYNCIODEBUG=1
    - ILOOP_TOKEN
    - ILOOP_API
    - MODEL_API
  command: ["-w", "1", "-b", "0.0.0.0:7000", "-t", "150", "-k", "aiohttp.worker.GunicornWebWorker", "iloop_to_model.app:app"]
