apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iloop-to-model
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - api.dd-decaf.eu
    secretName: decaf-tls
  rules:
  - host: api.dd-decaf.eu
    http:
      paths:
      - path: /iloop-to-model
        backend:
          serviceName: iloop-to-model-production
          servicePort: 80
